"""Response engines (brief §7.3): Minitaur served by LM Studio as the main engine, and the transparent
logistic baseline (eq. 17-18). Both see the same Trial and return the same Decision.

Minitaur facts this module is built on (all measured against the local server):
- It is a next-choice predictor trained on Psych-101: a prompt is a plain transcript and the learner's
  choice is the single token after `<<`. It cannot explain (it invents the next trial instead), so no
  free text is ever requested; the §7.3 `explanation` is the method behind the chosen option, which is
  known because every option is generated by a rule (correct method, documented misconception, distractor).
- The §7.3 output fields are therefore: answer (the pressed key and its value), confidence (a 1-5 rating
  pressed on a second scored trial, written back into the transcript), explanation (the option's method)
  and requested support (the help option, offered after a wrong answer).
- `/v1/completions` returns no logprobs. `/v1/chat/completions` with the transcript as an *assistant*
  message is continued as a prefill and returns `top_logprobs`, so a choice is *scored* there and then
  *sampled* from the renormalised distribution with the learner's seeded RNG (like Centaur at T = 1).
- Option letters and order are drawn at random per episode so any position bias becomes noise; measured
  2026-09-09 there is none left to speak of (mean P(first-listed) 0.30 over 151 three-option calls).
- Scores are not bitwise reproducible across calls (KV cache). Every call is appended to a JSONL log,
  and a run is reproduced by keeping that log, never by re-deriving it.
- Transient `HTTP 400 Engine protocol ... fetch failed` errors happen; they are retried.
"""
from __future__ import annotations

import hashlib
import json
import math
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

import numpy as np
import requests

from .learners import Learner, clip01, logistic

LETTERS = "BCDFGHJKLMNPQRSTVWXZ"  # option keys are drawn from here; no vowels, no A/E that read as words
APPROACH_QUESTION = "How do you want to approach this problem?"
APPROACH_TEXT = {  # the free-choice arm: option `kind` is the condition the learner picks (episode.py)
    "traditional": "Work through the hints on your own",
    "ai_scaffolding": "Talk it through with the AI tutor",
    "ai_substitution": "Ask the AI for the complete solution",
}
CONFIDENCE_KEYS = ("1", "2", "3", "4", "5")
CONFIDENCE_QUESTION = "How confident are you that this answer is correct, from 1 (guessing) to 5 (certain)?"
INSTRUCTIONS = (
    "You are taking part in a study on learning business analytics. On each trial you read a short lesson "
    "and a problem, then choose one option by pressing the corresponding key. Your choices are recorded "
    "between double angle brackets. After a wrong answer you may receive a hint or a message from a tutor, "
    "and then you choose again."
)
_LATENT = re.compile(r"\b(theta|alpha|delta|latent|b_u|brier|dependence|calibration)\b|\b[KMRCD]\s*=\s*\d", re.I)


class EngineError(RuntimeError):
    """The response engine cannot produce a usable answer; the run stops and can be resumed."""


@dataclass(frozen=True)
class Option:
    key: str
    kind: str  # correct | misconception | distractor | help
    text: str
    value: float | None = None
    method: str = ""  # the rule that produces this option's value; becomes the §7.3 `explanation` when chosen


@dataclass
class Trial:
    """One decision. Text fields are the observable transcript (Minitaur); numeric fields feed the
    logistic engine only. Latent state never travels here."""
    stage: str  # first | supported | transfer | probe | probe_supported
    lines: list[str]  # current-episode transcript so far
    options: list[Option]
    allow_help: bool = False
    b_u: float = 0.0
    support_h: float = 0.0
    record: str = ""  # "Your record so far: ..."
    history: list[str] = field(default_factory=list)  # compact renderings of past episodes


@dataclass
class Decision:
    key: str
    kind: str
    value: float | None
    p_correct: float
    p_by_key: dict
    confidence: float | None = None  # (rating - 1) / 4
    rating: int | None = None  # the 1-5 rating the learner pressed
    explanation: str | None = None  # method behind the chosen option, or "requested support"
    meta: dict = field(default_factory=dict)


def render_options(options) -> str:
    return "  ".join(f"{o.key}) {o.text}" for o in options)


def find_latent_leaks(text: str) -> list[str]:
    return sorted({m.group(0) for m in _LATENT.finditer(text)})


class Engine(Protocol):
    name: str

    def choose(self, trial: Trial, learner: Learner, rng: np.random.Generator) -> Decision: ...

    def confidence(self, trial: Trial, decision: Decision, learner: Learner, rng: np.random.Generator) -> float: ...


class MinitaurEngine:
    """The Psych-101 transcript engine. Minitaur and Centaur are the same protocol and differ only in
    the served model id, so `name` is read from config rather than hard-coded."""

    def __init__(self, cfg: dict, log_path: Path | None = None):
        self.name = cfg.get("name", "minitaur")
        self.base_url = cfg["base_url"].rstrip("/")
        self.model = cfg["model"]
        self.window = int(cfg.get("history_window", 3))
        self.top_logprobs = int(cfg.get("top_logprobs", 20))
        self.timeout = float(cfg.get("timeout_s", 180))
        self.max_attempts = int(cfg.get("max_attempts", 3))
        self.log_path = Path(log_path) if log_path else None
        self.calls = 0
        self.seconds = 0.0

    # -- transport ---------------------------------------------------------------------------
    def health_check(self) -> dict:
        try:
            ids = [m["id"] for m in requests.get(f"{self.base_url}/v1/models", timeout=10).json()["data"]]
        except Exception as exc:  # noqa: BLE001
            raise EngineError(f"cannot reach LM Studio at {self.base_url}: {exc}") from exc
        if self.model not in ids:
            raise EngineError(f"model {self.model!r} is not served; LM Studio lists {ids}")
        warmup = "\n".join([INSTRUCTIONS, "", "Problem 1.", "Question: What is 2 + 2?", "Options: Q) 4  W) 5", "You press <<"])
        _, meta = self.score(warmup, ("Q", "W"))
        return {"model": self.model, "warmup_mass_on_keys": meta["mass_on_keys"], "warmup_seconds": meta["seconds"]}

    def score(self, prompt: str, keys) -> tuple[dict, dict]:
        """Next-token distribution after `prompt`, renormalised onto `keys`. Token variants such as
        ' W' or 'w' are pooled onto the key they mean; a key outside the top-k gets a floor one nat
        below the lowest returned logprob and is reported in `missing_keys`."""
        payload = {"model": self.model, "messages": [{"role": "assistant", "content": prompt}], "max_tokens": 1,
                   "temperature": 0.0, "logprobs": True, "top_logprobs": self.top_logprobs}
        started, last = time.perf_counter(), None
        for attempt in range(self.max_attempts):
            try:
                r = requests.post(f"{self.base_url}/v1/chat/completions", json=payload, timeout=self.timeout)
                if r.status_code < 500 and not (r.status_code == 400 and "ngine" in r.text):
                    r.raise_for_status()
                    data = r.json()
                    break
                last = f"HTTP {r.status_code}: {r.text[:200]}"
            except (requests.ConnectionError, requests.Timeout) as exc:
                last = repr(exc)
            time.sleep(2.0 * (attempt + 1))
        else:
            raise EngineError(f"LM Studio failed {self.max_attempts} times; last error: {last}")
        seconds = time.perf_counter() - started
        try:
            top = data["choices"][0]["logprobs"]["content"][0]["top_logprobs"]
        except (KeyError, IndexError, TypeError) as exc:
            raise EngineError("the server returned no logprobs; scoring needs /v1/chat/completions with "
                              "logprobs=true (raw /v1/completions never returns them)") from exc
        mass = {k: 0.0 for k in keys}
        for e in top:
            tok = str(e["token"]).strip().upper()
            if tok in mass:
                mass[tok] += math.exp(e["logprob"])
        missing = [k for k in keys if mass[k] == 0.0]
        floor = math.exp(min(e["logprob"] for e in top) - 1.0)
        for k in missing:
            mass[k] = floor
        total = sum(mass.values())
        probs = {k: mass[k] / total for k in keys}
        meta = {"prompt_sha256": hashlib.sha256(prompt.encode("utf-8")).hexdigest(), "prompt_chars": len(prompt),
                "prompt_tokens": (data.get("usage") or {}).get("prompt_tokens"), "seconds": round(seconds, 3),
                "mass_on_keys": round(sum(mass[k] for k in keys if k not in missing), 4), "missing_keys": missing,
                "top_token": str(top[0]["token"]), "logprobs": {k: round(math.log(mass[k]), 4) for k in keys}}
        self.calls += 1
        self.seconds += seconds
        if self.log_path:
            with self.log_path.open("a", encoding="utf-8") as f:
                f.write(json.dumps({"model": self.model, "keys": list(keys), "probabilities": probs, **meta}) + "\n")
        return probs, meta

    # -- prompt (Psych-101 transcript) -------------------------------------------------------
    def prompt_for(self, trial: Trial) -> str:
        parts = [INSTRUCTIONS, ""]
        if trial.record:
            parts += [trial.record, ""]
        for past in trial.history[-self.window:]:
            parts += [past, ""]
        parts += trial.lines
        parts.append(f"Options: {render_options(trial.options)}")
        parts.append("You press <<")
        prompt = "\n".join(parts)
        leaks = find_latent_leaks(prompt)
        if leaks:
            raise EngineError(f"the prompt leaks latent learner state: {leaks}")
        return prompt

    # -- engine interface --------------------------------------------------------------------
    def choose(self, trial: Trial, learner: Learner, rng: np.random.Generator) -> Decision:
        keys = [o.key for o in trial.options]
        probs, meta = self.score(self.prompt_for(trial), keys)
        key = str(rng.choice(keys, p=[probs[k] for k in keys]))
        option = next(o for o in trial.options if o.key == key)
        p_correct = sum(probs[o.key] for o in trial.options if o.kind == "correct")
        return Decision(key, option.kind, option.value, float(p_correct), probs, explanation=explanation_of(option),
                        meta={"kind": "choice", **meta})

    def confidence(self, trial: Trial, decision: Decision, learner: Learner, rng: np.random.Generator) -> float:
        """A second scored trial: the rating is sampled like a choice and written back by the caller."""
        prompt = f"{self.prompt_for(trial)}{decision.key}>>.\n{CONFIDENCE_QUESTION} You press <<"
        probs, meta = self.score(prompt, CONFIDENCE_KEYS)
        decision.rating = int(rng.choice(CONFIDENCE_KEYS, p=[probs[k] for k in CONFIDENCE_KEYS]))
        decision.meta["confidence_call"] = {**meta, "expected_rating": sum(int(k) * p for k, p in probs.items())}
        return (decision.rating - 1) / 4.0


def explanation_of(option: Option) -> str:
    return "requested support" if option.kind == "help" else f"{option.kind}: {option.method}"


class LogisticEngine:
    """Eq. 17-18 plus a help-request model and a noisy confidence model. Deterministic given the RNG."""
    name = "logistic"

    def __init__(self, rcfg: dict, theta_slope: float):
        self.c = rcfg
        self.theta_slope = float(theta_slope)

    def _p(self, trial: Trial, learner: Learner) -> float:
        return float(logistic(learner.theta(self.theta_slope) - trial.b_u + self.c["rho"] * learner.R
                              + self.c["kappa"] * learner.M + self.c["omega"] * trial.support_h))

    def choose(self, trial: Trial, learner: Learner, rng: np.random.Generator) -> Decision:
        if trial.stage == "approach":
            return self.approach(trial, learner, rng)
        c, p = self.c, self._p(trial, learner)
        help_opt = next((o for o in trial.options if o.kind == "help"), None)
        if help_opt is not None and trial.allow_help:
            gap = learner.theta(self.theta_slope) - trial.b_u
            p_request = float(logistic(c["request_intercept"] + c["request_dependence_slope"] * learner.D
                                       - c["request_ability_slope"] * gap))
            if rng.random() < p_request:
                return Decision(help_opt.key, "help", None, p, {}, explanation=explanation_of(help_opt),
                                meta={"kind": "choice", "p_request": p_request})
        answers = [o for o in trial.options if o.kind != "help"]
        if rng.random() < p:
            option = next(o for o in answers if o.kind == "correct")
        else:
            wrong = [o for o in answers if o.kind != "correct"]
            misconception = [o for o in wrong if o.kind == "misconception"]
            others = [o for o in wrong if o.kind != "misconception"]
            if misconception and (not others or rng.random() < c["misconception_share"]):
                option = misconception[0]
            else:
                option = others[int(rng.integers(len(others)))]
        p_by_key = {o.key: (p if o.kind == "correct" else (1.0 - p) / max(1, len(answers) - 1)) for o in answers}
        return Decision(option.key, option.kind, option.value, p, p_by_key, explanation=explanation_of(option),
                        meta={"kind": "choice"})

    def approach(self, trial: Trial, learner: Learner, rng: np.random.Generator) -> Decision:
        """ASSUMPTION for the transparent baseline only: the free-choice arm is the transcript engine's
        job; here the choice is a softmax in the learner's dependence D (eq. 25), reusing the help-request
        slope: logit(substitution) = +s (D - 0.5), logit(traditional) = -s (D - 0.5), scaffolding = 0."""
        s = float(self.c["request_dependence_slope"]) * (learner.D - 0.5)
        logit = {"traditional": -s, "ai_scaffolding": 0.0, "ai_substitution": s}
        w = np.array([math.exp(logit[o.kind]) for o in trial.options])
        probs = {o.key: float(x) for o, x in zip(trial.options, w / w.sum())}
        option = trial.options[int(rng.choice(len(trial.options), p=list(probs.values())))]
        return Decision(option.key, option.kind, None, float("nan"), probs, explanation=f"approach: {option.kind}",
                        meta={"kind": "approach"})

    def confidence(self, trial: Trial, decision: Decision, learner: Learner, rng: np.random.Generator) -> float:
        """confidence = clip(p + bias_i + noise), reported on the same 1-5 scale as Minitaur."""
        decision.rating = 1 + int(round(4 * clip01(decision.p_correct + learner.confidence_bias
                                                   + rng.normal(0.0, self.c["confidence_noise_sd"]))))
        return (decision.rating - 1) / 4.0


class HybridEngine:
    """Centaur (or Minitaur) makes every behavioural choice - which approach to take, whether to ask for
    more help, the confidence rating - and the logistic model (eq. 17-18) decides whether an answer is
    correct. Measured 2026-09-10: the transcript models are at chance on the arithmetic itself, so the
    answer key never comes from them here; their distribution over the help key is kept exactly, by
    sampling it and handing a "not help" draw to the logistic engine."""
    name = "hybrid"

    def __init__(self, choice: MinitaurEngine, logistic: LogisticEngine):
        self.choice, self.logistic = choice, logistic

    def choose(self, trial: Trial, learner: Learner, rng: np.random.Generator) -> Decision:
        help_opt = next((o for o in trial.options if o.kind == "help"), None)
        if trial.stage == "approach" or (help_opt is not None and trial.allow_help):
            d = self.choice.choose(trial, learner, rng)
            if trial.stage == "approach" or d.kind == "help":
                return d
            choice_meta = d.meta
            trial = Trial(trial.stage, trial.lines, [o for o in trial.options if o.kind != "help"], False,
                          trial.b_u, trial.support_h, trial.record, trial.history)
        else:
            choice_meta = None
        d = self.logistic.choose(trial, learner, rng)
        if choice_meta is not None:  # keep the transcript call that decided "no help" in the record
            d.meta = {**d.meta, "choice_call": {k: v for k, v in choice_meta.items() if k != "kind"}}
        return d

    def confidence(self, trial: Trial, decision: Decision, learner: Learner, rng: np.random.Generator) -> float:
        return self.choice.confidence(trial, decision, learner, rng)
